[project]
name = "gigachad-bot"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "Agents-in-a-box @ git+ssh://git@github.com/patrickab/Agents-in-a-box.git",
    "ansi2html>=1.9.2",
    "litellm>=1.91.0",
    "llm-baseclient @ git+ssh://git@github.com/patrickab/llm-baseclient.git@main",
    "networkx>=3.6.1",
    "numpy>=2.4.6",
    "polars>=1.41.2",
    "plotly>=6.8.0",
    "pymupdf4llm>=1.27.2.3",
    "rag-database @ git+ssh://git@github.com/patrickab/rag-database.git@main",
    "st-copy>=1.1.2",
    "streamlit[pdf]>=1.57.0",
    "streamlit-ace>=0.1.1",
    "streamlit-agraph>=0.0.45",
    "streamlit-paste-button>=0.1.2",
    "tiktoken>=0.13.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.ruff]
target-version = "py312"
respect-gitignore = true
line-length = 135

[tool.ruff.lint]
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # isort
  "B",   # bugbear
  "C4",  # comprehensions
  "TCH", # type-checking hygiene
  "SIM", # simplify
  "ANN", # type hints
  "ARG", # unused arguments
  "RUF"  # Ruff-native rules
]
ignore = [
  "RuffTC001",
  "RUF100",
  "B904",
  "TC002"
]

[tool.ruff.lint.isort]
force-sort-within-sections = true
known-first-party = ["openai_client"]
section-order = ["standard-library", "third-party", "first-party", "local-folder"]

# Enables Ruff formatter with default options (Black-compatible)
[tool.ruff.format]
